package util


const (
	SERVER_TYPE_MASTER	= 1
	SERVER_TYPE_GATEWAY	= 2
	SERVER_TYPE_GAMESERVER	= 3
	SERVER_TYPE_LOBBY	= 4
	SERVER_TYPE_CACHE	= 5
	SERVER_TYPE_DBFE	= 6
	SERVER_TYPE_MONITOR	= 7
	SERVER_TYPE_STATICIS	= 8
)
